export const businessNiches = [
  { value: "ecommerce", label: "Электронная коммерция" },
  { value: "fintech", label: "Финансовые технологии" },
  { value: "healthtech", label: "Медицинские технологии" },
  { value: "edtech", label: "Образовательные технологии" },
  { value: "saas", label: "SaaS продукты" },
  { value: "food-delivery", label: "Доставка еды" },
  { value: "real-estate", label: "Недвижимость" },
  { value: "construction", label: "Строительство" },
  { value: "automotive", label: "Автомобильная индустрия" },
  { value: "fashion", label: "Мода и одежда" },
  { value: "beauty", label: "Красота и косметика" },
  { value: "fitness", label: "Фитнес и спорт" },
  { value: "travel", label: "Туризм и путешествия" },
  { value: "entertainment", label: "Развлечения" },
  { value: "gaming", label: "Игры и киберспорт" },
  { value: "media", label: "СМИ и контент" },
  { value: "marketing", label: "Маркетинг и реклама" },
  { value: "consulting", label: "Консалтинг" },
  { value: "legal", label: "Юридические услуги" },
  { value: "accounting", label: "Бухгалтерия и учет" },
  { value: "hr", label: "HR и рекрутинг" },
  { value: "logistics", label: "Логистика и доставка" },
  { value: "manufacturing", label: "Производство" },
  { value: "agriculture", label: "Сельское хозяйство" },
  { value: "energy", label: "Энергетика" },
  { value: "mining", label: "Добыча полезных ископаемых" },
  { value: "telecom", label: "Телекоммуникации" },
  { value: "security", label: "Безопасность" },
  { value: "cleaning", label: "Клининг и уборка" },
  { value: "repair", label: "Ремонт и обслуживание" },
  { value: "pet-care", label: "Уход за животными" },
  { value: "childcare", label: "Детские услуги" },
  { value: "elderly-care", label: "Услуги для пожилых" },
  { value: "photography", label: "Фотография" },
  { value: "design", label: "Дизайн" },
  { value: "architecture", label: "Архитектура" },
  { value: "music", label: "Музыка" },
  { value: "art", label: "Искусство" },
  { value: "crafts", label: "Рукоделие и ремесла" },
  { value: "jewelry", label: "Ювелирное дело" },
  { value: "watch", label: "Часы" },
  { value: "electronics", label: "Электроника" },
  { value: "appliances", label: "Бытовая техника" },
  { value: "furniture", label: "Мебель" },
  { value: "home-decor", label: "Декор для дома" },
  { value: "gardening", label: "Садоводство" },
  { value: "bookstore", label: "Книжный магазин" },
  { value: "stationery", label: "Канцелярские товары" },
  { value: "toys", label: "Игрушки" },
  { value: "pharmacy", label: "Фармацевтика" },
  { value: "dental", label: "Стоматология" },
  { value: "veterinary", label: "Ветеринария" },
  { value: "insurance", label: "Страхование" },
  { value: "banking", label: "Банковские услуги" },
  { value: "investment", label: "Инвестиции" },
  { value: "cryptocurrency", label: "Криптовалюты" },
  { value: "nonprofit", label: "Некоммерческие организации" },
  { value: "government", label: "Государственные услуги" },
  { value: "translation", label: "Переводческие услуги" },
  { value: "printing", label: "Полиграфия" },
  { value: "packaging", label: "Упаковка" },
  { value: "import-export", label: "Импорт-экспорт" },
  { value: "wholesale", label: "Оптовая торговля" },
  { value: "retail", label: "Розничная торговля" },
  { value: "franchise", label: "Франшиза" },
  { value: "affiliate", label: "Партнерский маркетинг" },
  { value: "dropshipping", label: "Дропшиппинг" },
  { value: "subscription", label: "Подписные услуги" },
  { value: "marketplace", label: "Маркетплейсы" },
  { value: "b2b", label: "B2B услуги" },
  { value: "b2c", label: "B2C услуги" },
  { value: "other", label: "Другое" },
];
