interface City {
  value: string;
  label: string;
}

export const russianCities: City[] = [
  { value: "moscow", label: "Москва" },
  { value: "saint-petersburg", label: "Санкт-Петербург" },
  { value: "novosibirsk", label: "Новосибирск" },
  { value: "yekaterinburg", label: "Екатеринбург" },
  { value: "kazan", label: "Казань" },
  { value: "nizhny-novgorod", label: "Нижний Новгород" },
  { value: "chelyabinsk", label: "Челябинск" },
  { value: "samara", label: "Самара" },
  { value: "omsk", label: "Омск" },
  { value: "rostov-on-don", label: "Ростов-на-Дону" },
  { value: "ufa", label: "Уфа" },
  { value: "krasnoyarsk", label: "Красноярск" },
  { value: "voronezh", label: "Воронеж" },
  { value: "perm", label: "Пермь" },
  { value: "volgograd", label: "Волгоград" },
  { value: "krasnodar", label: "Краснодар" },
  { value: "saratov", label: "Саратов" },
  { value: "tyumen", label: "Тюмень" },
  { value: "togliatti", label: "Тольятти" },
  { value: "izhevsk", label: "Ижевск" },
  { value: "barnaul", label: "Барнаул" },
  { value: "ulyanovsk", label: "Ульяновск" },
  { value: "irkutsk", label: "Иркутск" },
  { value: "vladivostok", label: "Владивосток" },
  { value: "yaroslavl", label: "Ярославль" },
  { value: "makhachkala", label: "Махачкала" },
  { value: "tomsk", label: "Томск" },
  { value: "orenburg", label: "Оренбург" },
  { value: "kemerovo", label: "Кемерово" },
  { value: "novokuznetsk", label: "Новокузнецк" },
  { value: "ryazan", label: "Рязань" },
  { value: "naberezhnye-chelny", label: "Набережные Челны" },
  { value: "astrakhan", label: "Астрахань" },
  { value: "lipetsk", label: "Липецк" },
  { value: "tula", label: "Тула" },
  { value: "kirov", label: "Киров" },
  { value: "cheboksary", label: "Чебоксары" },
  { value: "kaliningrad", label: "Калининград" },
  { value: "bryansk", label: "Брянск" },
  { value: "magnitogorsk", label: "Магнитогорск" },
  { value: "ivanovo", label: "Иваново" },
  { value: "tver", label: "Тверь" },
  { value: "stavropol", label: "Ставрополь" },
  { value: "belgorod", label: "Белгород" },
  { value: "sochi", label: "Сочи" },
  { value: "nizhny-tagil", label: "Нижний Тагил" },
  { value: "vladimir", label: "Владимир" },
  { value: "arkhangelsk", label: "Архангельск" },
  { value: "kaluga", label: "Калуга" },
  { value: "chita", label: "Чита" },
  { value: "saransk", label: "Саранск" },
  { value: "surgut", label: "Сургут" },
  { value: "vologda", label: "Вологда" },
  { value: "tambov", label: "Тамбов" },
  { value: "murmansk", label: "Мурманск" },
  { value: "vladikavkaz", label: "Владикавказ" },
  { value: "cherepovets", label: "Череповец" },
  { value: "yakutsk", label: "Якутск" },
  { value: "grozny", label: "Грозный" },
  { value: "kostroma", label: "Кострома" },
  { value: "komsomolsk-on-amur", label: "Комсомольск-на-Амуре" },
  { value: "petrozavodsk", label: "Петрозаводск" },
  { value: "nizhnevartovsk", label: "Нижневартовск" },
  { value: "yoshkar-ola", label: "Йошкар-Ола" },
  { value: "novorossiysk", label: "Новороссийск" },
  { value: "khabarovsk", label: "Хабаровск" },
  { value: "smolensk", label: "Смоленск" },
  { value: "orsk", label: "Орск" },
  { value: "stary-oskol", label: "Старый Оскол" },
  { value: "kursk", label: "Курск" },
  { value: "engels", label: "Энгельс" },
  { value: "dzerzhinsk", label: "Дзержинск" },
  { value: "blagoveshchensk", label: "Благовещенск" },
  { value: "great-novgorod", label: "Великий Новгород" },
  { value: "pskov", label: "Псков" },
];
